### ISSUE TITLE
vite.config.js

### ISSUE THREAD

**Issue by thewind11235** [themeselection/sneat-vuetify-vuejs-laravel-admin-template-free#1]
### Steps to reproduce

i setup new project follow your guide. After that, i create a api to test with new vue file

### What is expected?

i wanna you check /resources/js/plugins/axios and clean error

### What is actually happening?

my terminal show error can't find aixos at /resources/js/plugins/ :
Failed to load url /resources/js/plugins/axios (resolved id: .../appdemo/resources/js/plugins/axios) in .../appdemo/resources/js/pages/test.vue. Does the file exist?
in vite config:
'@axios': fileURLToPath(new URL('./resources/js/plugins/axios', import.meta.url)),
it running after i change to '@axios': fileURLToPath(new URL('./node_modules/axios', import.meta.url)), but extension eslint still notif: Unable to resolve path to module '@axios'.

![Screenshot 2023-07-15 at 01 52 50](https://github.com/themeselection/sneat-vuetify-vuejs-laravel-admin-template-free/assets/33033549/bbc13907-e1e5-4992-8476-74506e471758)

**Comment by DeepKumbhare85** [comment]
Hello @thewind11235 ,
Thank you for getting in touch with us.

We request you to remove the '@axios' alias from 'vite.config.js' file as it is not included in our free version. After removing the line, you should be able to integrate Axios into your page, and it will function properly. Thank you for your understanding.
