### ISSUE TITLE
consider changing `roboto` source

### ISSUE THREAD

**Issue by xerc** [themeselection/sneat-vuetify-vuejs-laravel-admin-template-free#2]
### What problem does this feature solve?

latest glyphs

### What does the proposed solution look like?

https://www.npmjs.com/package/@fontsource/roboto

**Comment by alokVishu** [comment]
Hello @xerc,

Thanks for getting in touch with us.

Can you provide more details about the problem you are experiencing? It would be helpful if you could also attach any relevant screenshots or videos to help illustrate the issue.

Awaiting your reply.
Best regards

**Comment by xerc** [comment]
check https://github.com/choffmeister/roboto-fontface-bower#roboto-fontface

**Comment by alokVishu** [comment]
Hello @xerc,

Thank you for the reply. 

We will take into consideration the possibility of updating the font-face in our upcoming release. However, feel free to update the font face in your current project in the meantime.

Let me know if you have any further queries.

**Comment by xerc** [comment]
thanks // are you also considering `inertia`?

**Comment by alokVishu** [comment]
Hello @xerc,

At this time, we are not planning to incorporate inertia implementation.

Best Regards
