### ISSUE TITLE
Could not resolve dependency stylelint when using npm for installation

### ISSUE THREAD

**Issue by nixprosoft** [themeselection/sneat-vuetify-vuejs-laravel-admin-template-free#4]
### Steps to reproduce

`npm install`

### What is expected?

Success installation.

### What is actually happening?

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: sneat-vuetify-vuejs-laravel-admin-template-free@2.0.0
npm error Found: stylelint@16.2.1
npm error node_modules/stylelint
npm error   dev stylelint@"16.2.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peer stylelint@"^15.11.0" from stylelint-codeguide@0.3.2
npm error node_modules/stylelint-codeguide
npm error   dev stylelint-codeguide@"0.3.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\nikit\AppData\Local\npm-cache\_logs\2024-11-19T12_54_21_072Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\nikit\AppData\Local\npm-cache\_logs\2024-11-19T12_54_21_072Z-debug-0.log

### Additional data

NodeJS Version: LTS 22
Package manager: npm 10.9.0
System: Win 10

**Comment by yagnikvamja** [comment]
Hello @nixprosoft ,

We highly recommend using `pnpm` as it offers better resolution of peer dependencies.

While we consistently maintain our library, but `npm` is unable to resolve peer dependencies. To address this issue using `npm`, please run the following command as it helps in resolving peer dependencies.
```
npm install --legacy-peer-deps
```
This should allow the installation to proceed without errors.

~Best regards,
